# Generated by Django 3.0.7 on 2020-10-01 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20201001_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Plan name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='Period')),
                ('period_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=20, verbose_name='Period unit')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('currency_code', models.CharField(choices=[('us', 'USD'), ('eur', 'EUR'), ('pln', 'PLN')], max_length=10, verbose_name='Currency')),
                ('recurring', models.BooleanField(blank=True, default=False, verbose_name='Recurring')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='main.Product')),
            ],
            bases=(models.Model, main.models.CreateModMixin),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status')),
                ('recurring', models.BooleanField(blank=True, default=False, verbose_name='Recurring')),
                ('term_start', models.DateTimeField(blank=True, null=True, verbose_name='Term start')),
                ('term_end', models.DateTimeField(blank=True, null=True, verbose_name='Term end')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='main.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, main.models.CreateModMixin),
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Plan name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('value_unit', models.CharField(max_length=120, verbose_name='Value unit')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.Plan')),
            ],
            bases=(models.Model, main.models.CreateModMixin),
        ),
    ]
