# Generated by Django 3.0.7 on 2020-09-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200809_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=120, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('country', models.CharField(max_length=60, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number')),
                ('is_billing', models.BooleanField(default=True)),
                ('billing_address1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Billing address')),
                ('billing_address2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Billing address')),
                ('billing_city', models.CharField(blank=True, max_length=60, null=True, verbose_name='Billing city')),
                ('billing_postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Billing postcode')),
                ('billing_country', models.CharField(blank=True, max_length=60, null=True, verbose_name='Billing country')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
