# Generated by Django 3.0 on 2020-08-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200809_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=120, null=True, verbose_name='Company name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone number')),
                ('line1', models.CharField(blank=True, max_length=120, null=True)),
                ('line2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=60)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('for_billing', models.BooleanField(default=False)),
                ('company_address', models.CharField(max_length=120)),
                ('company_address2', models.CharField(blank=True, max_length=120, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=30, null=True)),
                ('business', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_firstname', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_lastname', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=60, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
